<?php

namespace App\DataFixtures;

use App\Entity\Category;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class CategoryFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $categories = [
            'Electronics',
            'Clothing',
            'Books',
            'Home & Garden',
            'Sports & Outdoors',
            'Toys & Games'
        ];

        foreach ($categories as $index => $categoryName) {
            $category = new Category();
            $category->setName($categoryName);
            // Slug will be auto-generated by your PrePersist hook!
            
            $manager->persist($category);
            
            // Store reference for use in ProductFixtures
            $this->addReference('category_' . $index, $category);
        }

        $manager->flush();
    }
}