<?php

namespace App\DataFixtures;

use App\Entity\Product;
use App\Entity\Category;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class ProductFixtures extends Fixture implements DependentFixtureInterface
{
    private const PRODUCT_TYPE_MAP = [
    'Smartphone'    => 'smartphone',
    'Laptop'        => 'laptop',
    'Tablet'        => 'tablet',
    'Headphones'    => 'headphones',
    'Smart Watch'   => 'smart_watch',
    'Camera'        => 'camera',
    'Speaker'       => 'speaker',
    'Monitor'       => 'monitor',
    'Keyboard'      => 'keyboard',
    'Mouse'         => 'mouse',
    'T-Shirt'       => 'tshirt',
    'Jeans'         => 'jeans',
    'Jacket'        => 'jacket',
    'Dress'         => 'dress',
    'Sweater'       => 'sweater',
    'Shorts'        => 'shorts',
    'Hat'           => 'hat',
    'Scarf'         => 'scarf',
    'Hoodie'        => 'hoodie',
    'Sneakers'      => 'sneakers',
    'Novel'         => 'novel',
    'Cookbook'      => 'cookbook',
    'Guide'         => 'guide',
    'Biography'     => 'biography',
    'Textbook'      => 'textbook',
    'Magazine'      => 'magazine',
    'Journal'       => 'journal',
    'Dictionary'    => 'dictionary',
    'Encyclopedia'  => 'encyclopedia',
    'Lamp'          => 'lamp',
    'Chair'         => 'chair',
    'Table'         => 'table',
    'Vase'          => 'vase',
    'Rug'           => 'rug',
    'Plant Pot'     => 'plant_pot',
    'Tool Set'      => 'tool_set',
    'Storage Box'   => 'storage_box',
    'Cushion'       => 'cushion',
    'Curtain'       => 'curtain',
    'Yoga Mat'      => 'yoga_mat',
    'Dumbbell'      => 'dumbbell',
    'Tent'          => 'tent',
    'Backpack'      => 'backpack',
    'Bicycle'       => 'bicycle',
    'Fishing Rod'   => 'fishing_rod',
    'Soccer Ball'   => 'soccer_ball',
    'Tennis Racket' => 'tennis_racket',
    'Camping Stove' => 'camping_stove',
    'Puzzle'        => 'puzzle',
    'Board Game'    => 'board_game',
    'Action Figure' => 'action_figure',
    'Doll'          => 'doll',
    'Building Set'  => 'building_set',
    'Stuffed Animal'=> 'stuffed_animal',
    'Remote Car'    => 'remote_car',
    'Lego Set'      => 'lego_set',
    'Dinosaur Toy'  => 'dinosaur_toy',
];
    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create();
        
        // Get all category references
        $categories = [];
        for ($i = 0; $i < 6; $i++) {
            $categories[] = $this->getReference('category_' . $i, Category::class);
        }

        // Create 30 products
        for ($i = 0; $i < 30; $i++) {
            $product = new Product();
            
            // Random category
            $randomCategory = $categories[array_rand($categories)];
            $product->setCategory($randomCategory);
            
            // Product name with realistic product names
            $productName = $this->generateProductName($faker, $randomCategory->getName());
            $product->setName($productName);
            // Slug will be auto-generated by your PrePersist hook!
            
            // Description - longer, realistic product description
            $product->setDescription($faker->paragraphs(rand(2, 4), true));
            
            // Price - between $5 and $500, with 2 decimal places (stored as string)
            $price = $faker->randomFloat(2, 5, 500);
            $product->setPrice((string) $price);
            
            // Stock - between 0 and 100
            $stock = $faker->numberBetween(0, 100);
            $product->setStock($stock);
            
            // Image filename - using placeholder images (you can use real images later)
            $product->setImageFilename($this->generateImageFilename($randomCategory->getName(), $productName));
            
            // isActive - 90% of products are active
            $product->setIsActive($faker->boolean(90));
            
            // CreatedAt is auto-set by PrePersist, but you can override for variety
            // To have varied creation dates, set it manually
            $createdAt = $faker->dateTimeBetween('-1 year', 'now');
            $product->setCreatedAt(\DateTimeImmutable::createFromMutable($createdAt));
            
            $manager->persist($product);
        }

        $manager->flush();
    }

    private function generateProductName($faker, string $category): string
    {
        $adjectives = ['Premium', 'Deluxe', 'Professional', 'Compact', 'Essential', 'Ultimate', 'Basic', 'Advanced', 'Smart', 'Eco-Friendly'];
        $brands = ['TechPro', 'SmartLife', 'ComfortWear', 'ReadWell', 'HomeStyle', 'ActiveGear', 'PlayTime', 'Elite', 'ValuePlus'];
        
        $productTypes = [
            'Electronics' => ['Smartphone', 'Laptop', 'Tablet', 'Headphones', 'Smart Watch', 'Camera', 'Speaker', 'Monitor', 'Keyboard', 'Mouse'],
            'Clothing' => ['T-Shirt', 'Jeans', 'Jacket', 'Dress', 'Sweater', 'Shorts', 'Hat', 'Scarf', 'Hoodie', 'Sneakers'],
            'Books' => ['Novel', 'Cookbook', 'Guide', 'Biography', 'Textbook', 'Magazine', 'Journal', 'Dictionary', 'Encyclopedia'],
            'Home & Garden' => ['Lamp', 'Chair', 'Table', 'Vase', 'Rug', 'Plant Pot', 'Tool Set', 'Storage Box', 'Cushion', 'Curtain'],
            'Sports & Outdoors' => ['Yoga Mat', 'Dumbbell', 'Tent', 'Backpack', 'Bicycle', 'Fishing Rod', 'Soccer Ball', 'Tennis Racket', 'Camping Stove'],
            'Toys & Games' => ['Puzzle', 'Board Game', 'Action Figure', 'Doll', 'Building Set', 'Stuffed Animal', 'Remote Car', 'Lego Set', 'Dinosaur Toy']
        ];
        
        $adjective = $faker->randomElement($adjectives);
        $brand = $faker->randomElement($brands);
        
        $typeList = $productTypes[$category] ?? ['Product', 'Item', 'Accessory'];
        $type = $faker->randomElement($typeList);
        
        // Different naming patterns
        $pattern = $faker->numberBetween(1, 4);
        
        switch ($pattern) {
            case 1:
                return $brand . ' ' . $type;
            case 2:
                return $adjective . ' ' . $type;
            case 3:
                return $brand . ' ' . $adjective . ' ' . $type;
            default:
                return $type . ' ' . $faker->randomElement(['Pro', 'Max', 'Plus', 'Lite', 'X']);
        }
    }

    private function generateImageFilename(string $categoryName, string $productName): string
{
    $folder = strtolower(str_replace(' & ', '_', $categoryName));

    // Try to find a matching product type in the name
    foreach (self::PRODUCT_TYPE_MAP as $productType => $fileKey) {
        if (stripos($productName, $productType) !== false) {
            return "{$folder}/{$fileKey}.jpg";
        }
    }

    // Fallback: pick a random file from the folder (should rarely happen)
    $fallbackKeys = array_values(self::PRODUCT_TYPE_MAP);
    return "{$folder}/" . $fallbackKeys[array_rand($fallbackKeys)] . ".jpg";
}

    public function getDependencies(): array
    {
        return [
            CategoryFixtures::class,
        ];
    }
}