<?php

namespace App\DataFixtures;

use App\Entity\Product;
use App\Entity\Category;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class ProductFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create();
        
        // Get all category references
        $categories = [];
        for ($i = 0; $i < 6; $i++) {
            $categories[] = $this->getReference('category_' . $i, Category::class);
        }

        // Create 30 products
        for ($i = 0; $i < 30; $i++) {
            $product = new Product();
            
            // Random category
            $randomCategory = $categories[array_rand($categories)];
            $product->setCategory($randomCategory);
            
            // Product name with realistic product names
            $productName = $this->generateProductName($faker, $randomCategory->getName());
            $product->setName($productName);
            // Slug will be auto-generated by your PrePersist hook!
            
            // Description - longer, realistic product description
            $product->setDescription($faker->paragraphs(rand(2, 4), true));
            
            // Price - between $5 and $500, with 2 decimal places (stored as string)
            $price = $faker->randomFloat(2, 5, 500);
            $product->setPrice((string) $price);
            
            // Stock - between 0 and 100
            $stock = $faker->numberBetween(0, 100);
            $product->setStock($stock);
            
            // Image filename - using placeholder images (you can use real images later)
            $product->setImageFilename($this->generateRandomImage());
            
            // isActive - 90% of products are active
            $product->setIsActive($faker->boolean(90));
            
            // CreatedAt is auto-set by PrePersist, but you can override for variety
            // To have varied creation dates, set it manually
            $createdAt = $faker->dateTimeBetween('-1 year', 'now');
            $product->setCreatedAt(\DateTimeImmutable::createFromMutable($createdAt));
            
            $manager->persist($product);
        }

        $manager->flush();
    }

    private function generateProductName($faker, string $category): string
    {
        $adjectives = ['Premium', 'Deluxe', 'Professional', 'Compact', 'Essential', 'Ultimate', 'Basic', 'Advanced', 'Smart', 'Eco-Friendly'];
        $brands = ['TechPro', 'SmartLife', 'ComfortWear', 'ReadWell', 'HomeStyle', 'ActiveGear', 'PlayTime', 'Elite', 'ValuePlus'];
        
        $productTypes = [
            'Electronics' => ['Smartphone', 'Laptop', 'Tablet', 'Headphones', 'Smart Watch', 'Camera', 'Speaker', 'Monitor', 'Keyboard', 'Mouse'],
            'Clothing' => ['T-Shirt', 'Jeans', 'Jacket', 'Dress', 'Sweater', 'Shorts', 'Hat', 'Scarf', 'Hoodie', 'Sneakers'],
            'Books' => ['Novel', 'Cookbook', 'Guide', 'Biography', 'Textbook', 'Magazine', 'Journal', 'Dictionary', 'Encyclopedia'],
            'Home & Garden' => ['Lamp', 'Chair', 'Table', 'Vase', 'Rug', 'Plant Pot', 'Tool Set', 'Storage Box', 'Cushion', 'Curtain'],
            'Sports & Outdoors' => ['Yoga Mat', 'Dumbbell', 'Tent', 'Backpack', 'Bicycle', 'Fishing Rod', 'Soccer Ball', 'Tennis Racket', 'Camping Stove'],
            'Toys & Games' => ['Puzzle', 'Board Game', 'Action Figure', 'Doll', 'Building Set', 'Stuffed Animal', 'Remote Car', 'Lego Set', 'Dinosaur Toy']
        ];
        
        $adjective = $faker->randomElement($adjectives);
        $brand = $faker->randomElement($brands);
        
        $typeList = $productTypes[$category] ?? ['Product', 'Item', 'Accessory'];
        $type = $faker->randomElement($typeList);
        
        // Different naming patterns
        $pattern = $faker->numberBetween(1, 4);
        
        switch ($pattern) {
            case 1:
                return $brand . ' ' . $type;
            case 2:
                return $adjective . ' ' . $type;
            case 3:
                return $brand . ' ' . $adjective . ' ' . $type;
            default:
                return $type . ' ' . $faker->randomElement(['Pro', 'Max', 'Plus', 'Lite', 'X']);
        }
    }

    private function generateRandomImage(): string
    {
        // Using placeholder images from picsum.photos or similar
        // You can replace these with actual image files in your public/uploads directory
        $images = [
            'product1.jpg',
            'product2.jpg',
            'product3.jpg',
            'product4.jpg',
            'product5.jpg',
            'product6.jpg',
            'product7.jpg',
            'product8.jpg',
            'product9.jpg',
            'product10.jpg'
        ];
        
        // For now, return a placeholder image name
        // You can download sample images or use a service like:
        // https://picsum.photos/400/400?random={$random}
        
        $randomImage = $images[array_rand($images)];
        
        // Alternative: Use LoremFlick placeholder (requires internet)
        // return 'https://picsum.photos/id/' . rand(1, 100) . '/400/400';
        
        return $randomImage;
    }

    public function getDependencies(): array
    {
        return [
            CategoryFixtures::class,
        ];
    }
}